[package]
name = "poc_pcd"
version = "0.1.0"
edition = "2021"
default-run = "extract_convert"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dotenv = "0.15.0"